# Registering on eureka server at localhost:8010
# Common to all profiles
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8010/eureka/
#      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
management:
  endpoint:
    features:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include:
        - "*"